# Zifan Yang 
# zyang45@jhu.edu

default: 
	@echo "------using Python so nothing to make---------"

# cat_0:cat0.cpp
# 	g++ cat0.cpp -o cat0.o
# 	@echo "-------cat0 ok (c++)-------"

# cat_3:cat3.scala
# 	scalac cat3.scala
# 	@echo "-------cat3 ok (scala)-----"

# cat_4:cat4.java
# 	javac -g cat4.java
# 	@echo "-------cat4 ok (java)------"


clean: 
	rm -rf *.pyc  *.ps *.png *.dot